In [1]:
import numpy as np
B = np.arange(3)
print(B)
#print np.exp(B)
print(np.sqrt(B))

[0 1 2]
[ 0.          1.          1.41421356]


In [4]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print(a)

print(a.shape)
## flatten the array
print(a.ravel())
a.shape = (6, 2)
print(a) 
print(a.T)
a.resize((2,6))
print(a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)

[[ 9.  1.  2.  8.]
 [ 4.  3.  5.  3.]
 [ 2.  6.  3.  2.]]
(3, 4)
[ 9.  1.  2.  8.  4.  3.  5.  3.  2.  6.  3.  2.]
[[ 9.  1.]
 [ 2.  8.]
 [ 4.  3.]
 [ 5.  3.]
 [ 2.  6.]
 [ 3.  2.]]
[[ 9.  2.  4.  5.  2.  3.]
 [ 1.  8.  3.  3.  6.  2.]]
[[ 9.  1.  2.  8.  4.  3.]
 [ 5.  3.  2.  6.  3.  2.]]


In [7]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('---'*5)
print(b)
print('---'*5)
print(np.hstack((a,b))) #水平组合
#np.hstack((a,b))

[[ 0.  0.]
 [ 2.  9.]]
---------------
[[ 1.  8.]
 [ 9.  4.]]
---------------
[[ 0.  0.  1.  8.]
 [ 2.  9.  9.  4.]]


In [37]:
a = np.floor(10*np.random.random((2,12)))
#print a
#print np.hsplit(a,3)
#print np.hsplit(a,(3,4))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print a
np.vsplit(a,3) #垂直拆分

[[ 5.  2.]
 [ 1.  3.]
 [ 9.  6.]
 [ 2.  2.]
 [ 7.  2.]
 [ 8.  2.]
 [ 1.  7.]
 [ 2.  8.]
 [ 4.  4.]
 [ 8.  5.]
 [ 4.  3.]
 [ 2.  3.]]


[array([[ 5.,  2.],
        [ 1.,  3.],
        [ 9.,  6.],
        [ 2.,  2.]]), array([[ 7.,  2.],
        [ 8.,  2.],
        [ 1.,  7.],
        [ 2.,  8.]]), array([[ 4.,  4.],
        [ 8.,  5.],
        [ 4.,  3.],
        [ 2.,  3.]])]

In [9]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a #同一对象的不同别名。
# a and b are two names for the same ndarray object
b is a
b.shape = 3,4
print(a.shape)
print(id(a))
print(id(b))

(3, 4)
94787744
94787744


In [10]:
#The view method creates a new array object that looks at the same data.
c = a.view()#创建新的array对象，但改变其中的内容会影响之前的内容。
c is a
print(id(a))
print(id(c))
c.shape = 2,6
#print a.shape
c[0,4] = 1234
a

94787744
94785984


array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [13]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() #完全的拷贝，是不同的对象。
print(d is a)
print(id(a))
print(id(d))
d[0,0] = 9999
print(d) 
print(a)

False
94787744
94877536
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
