In [1]:
import numpy
#it will compare the second value to each element in the vector
# If the values are equal, the Python interpreter returns True; otherwise, it returns False
vector = numpy.array([5, 10, 15, 20])#初始化数组
vector == 10 #数据中元素如果等于比较值，对应值返回true，否则返回false。返回的结果为布尔值的数据。

array([False,  True, False, False], dtype=bool)

In [4]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
matrix == 25  #多维数组比较具体值，返回多维数组的bool类型的多维数组。

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [5]:
#Compares vector to the value 10, which generates a new Boolean vector [False, True, False, False]. It assigns this result to equal_to_ten
vector = numpy.array([5, 10, 15, 20])#初始化一维数组。
equal_to_ten = (vector == 10)#数组比较值，返回数组值的bool类型的数组。
print(equal_to_ten)#打印bool类型的数组。
print(vector[equal_to_ten])#数组中传入bool类型的数组，返回true对应的元素。

[False  True False False]
[10]


In [9]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 25, 45]
             ])
second_column_25 = (matrix[:,1] == 25)  #多维数组中，所有行中第二个元素是否等于25.
print(second_column_25)  #比较值是否匹配，对应的bool的数组。
print(matrix[second_column_25, :])#根据是否匹配比较值，打印所在的行。

[False  True  True]
[[20 25 30]
 [35 25 45]]


In [10]:
#We can also perform comparisons with multiple conditions
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5) #bool类型的矩阵的逻辑与.
print(equal_to_ten_and_five)

[False False False False]


In [11]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5) #匹配多个元素，bool类型的逻辑或。
print(equal_to_ten_or_five)

[ True  True False False]


In [13]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5) #获取到数组中等于10或者5的bool类型的逻辑或。
print(equal_to_ten_or_five)
vector[equal_to_ten_or_five] = 50 #原数组中根据bool的索引设定对应值为50.
print(vector)

[ True  True False False]
[50 50 15 20]


In [15]:
matrix = numpy.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
second_column_25 = matrix[:,1] == 25 #多维数组中，每一行中第二列数据等于25.
print(second_column_25) #比对后获取到行的bool类型。
matrix[second_column_25, 1] = 10 #对应每一行中，行的bool为true时把改行的第二数组设定为10.
print(matrix)

[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [16]:
#We can convert the data type of an array with the ndarray.astype() method.
vector = numpy.array(["1", "2", "3"]) #初始化字符串的数组
print(vector.dtype)#打印数组的数据类型 
print(vector)
vector = vector.astype(float)#数据类型设定为浮点型
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[ 1.  2.  3.]


In [17]:
vector = numpy.array([5, 10, 15, 20])
vector.sum() #数组元素整体求和
help(vector.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



In [18]:
# The axis dictates which dimension we perform the operation on
#1 means that we want to perform the operation on each row, and 0 means on each column
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(axis=1) #多维数组按照轴求值。axis=1表示按照行。

array([ 30,  75, 120])

In [19]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(axis=0)##多维数组按照轴求值。axis=0表示按照列。


array([60, 75, 90])

In [26]:
#replace nan value with 0
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",")
#print(world_alcohol[1])
is_value_empty = numpy.isnan(world_alcohol[:,4]) #数据中第五个元素是否为nan
#print(is_value_empty)
world_alcohol[is_value_empty, 4] = '0' #根据之前判断是否空，对每一行中第五个元素如果为nan的话，重新设定为'0'
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float) #设定为浮点型
total_alcohol = alcohol_consumption.sum()#计算总和
average_alcohol = alcohol_consumption.mean()#计算平均值
print(total_alcohol)
print(average_alcohol)

1137.78
1.14006012024
