In [12]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
print('---'*5)
print(data.shape[1])
print(range(data.shape[1]))
print('---'*5)
ind = data.argmax(axis=0) #按照列，找去每一列中最大值的索引值。
print(ind)
data_max = data[ind, range(data.shape[1])]
data_max = data[ind]
print(data_max)
#all(data_max == data.max(axis=0))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
---------------
4
range(0, 4)
---------------
[2 0 3 1]
[[ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [ 0.          0.84147098  0.90929743  0.14112001]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]]


In [16]:
a = np.arange(0, 40, 10)
b = np.tile(a, (3, 5)) 
print b

[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


a = np.arange(0, 40, 10)
print a
print '---'
b = np.tile(a, (1, 4))
print b
#print a
#print b


In [8]:
a = np.array([[4, 3, 5], [1, 2, 1]])
#print a
#b = np.sort(a, axis=1)
#print b
#b
#a.sort(axis=1)
#print a
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print j
print a[j]

[2 3 1 0]
[1 2 3 4]
