In [1]:
import numpy

world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",") #导入数据，路径和分隔符号。
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [3]:
#The numpy.array() function can take a list or list of lists as input. When we input a list, we get a one-dimensional array as a result:
vector = numpy.array([5, 10, 15, 20]) #列表元素的初始化，一维数组。元素的类型都是一样。
#When we input a list of lists, we get a matrix as a result:
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])#多维数组初始化。
print vector#一维数组
print matrix#矩阵

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
#We can use the ndarray.shape property to figure out how many elements are in the array
vector = numpy.array([1, 2, 3, 4])
print(vector.shape)  #获取到数组的元素个数
#For matrices, the shape property contains a tuple with 2 elements.
matrix = numpy.array([[5, 10, 15], [20, 25, 30]]) #多维数组
print(matrix.shape)#多维数组的形状

(4,)
(2, 3)


In [5]:
#Each value in a NumPy array has to have the same data type #每个数组中元素的类型是一致的。
#NumPy will automatically figure out an appropriate data type when reading in data or converting lists to arrays. 自动转化数组元素的类型。
#You can check the data type of a NumPy array using the dtype property.
numbers = numpy.array([1, 2, 3, 4])
numbers.dtype #数组元素类型的查看

dtype('int32')

In [10]:
#When NumPy can't convert a value to a numeric data type like float or integer, it uses a special nan value that stands for Not a Number
#nan is the missing data  导入数据时，无法转化，用nan代替。
#1.98600000e+03 is actually 1.986 * 10 ^ 3
world_alcohol

array([[             nan,              nan,              nan,
                     nan,              nan],
       [  1.98600000e+03,              nan,              nan,
                     nan,   0.00000000e+00],
       [  1.98600000e+03,              nan,              nan,
                     nan,   5.00000000e-01],
       ..., 
       [  1.98700000e+03,              nan,              nan,
                     nan,   7.50000000e-01],
       [  1.98900000e+03,              nan,              nan,
                     nan,   1.50000000e+00],
       [  1.98500000e+03,              nan,              nan,
                     nan,   3.10000000e-01]])

In [4]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1) #重新导入，数据的类型为字符串。
print(world_alcohol)  #打印整个数据,不包含第一行的列标题。
print(world_alcohol.size)#打印数据的个数。997*5
print(world_alcohol.shape)#数据的维数
print(world_alcohol[0,0])

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
4985
(997, 5)
1986


In [12]:
uruguay_other_1986 = world_alcohol[1,4]  #取第二行中第五个元素。
third_country = world_alcohol[2,2] #取三行中第三个元素。
print uruguay_other_1986
print third_country

0.5
Cte d'Ivoire


In [13]:
vector = numpy.array([5, 10, 15, 20])
print(vector[0:3])  #切片取值，不包括右边界。

[ 5 10 15]


In [14]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,1])#矩阵取值，行不限制，列上取第二个值。

[10 25 40]


In [15]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,0:2]) #矩阵中取值，行不限制，列切片取值，取前两个值。

[[ 5 10]
 [20 25]
 [35 40]]


In [12]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[1:3,0:2]) #多维数组切片取值。

[[20 25]
 [35 40]]
